[[redirects]]
  from = "/signup"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/enterprise"
  to = "/solutions.html"
  status = 200

[[redirects]]
  from = "/legal"
  to = "/solutions.html"
  status = 200

[[redirects]]
  from = "/finance"
  to = "/solutions.html"
  status = 200

[[redirects]]
  from = "/healthcare"
  to = "/solutions.html"
  status = 200

[[redirects]]
  from = "/platform"
  to = "/platform.html"
  status = 200

[[redirects]]
  from = "/security"
  to = "/security.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/demo.html"
  status = 200

